apiVersion: v1
kind: Pod
metadata:
  name: centos-sleeper-pod
  labels:
    app: ubuntu
spec:
  containers:
    - image: busybox
      name: sleeper-container
      commands: ["/bin/sh","-c"]
      args: ["sleep","1000"]