apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-replicaset
  labels:
    app: nginx
    cont: rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      env: dev
  template:
    metadata:
      name: nginx-pod-rs
      labels:
        app:  nginx
        env: dev
    spec:
      containers:
        - image: nginx
          name: nginx-cont

