apiVersion: v1
kind: Service
metadata:
  name: nginx-rs-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30085
  selector:
    app: nginx
    env: dev
    
