apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: polinux-stress-pod
  name: polinux-stress-pod
spec:
  containers:
  - image: polinux/stress
    name: polinux-stress-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
