apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-httpd
  labels:
    app: httpd
    tier: frontend
spec:
  template:
    metadata: 
      name: httpd-pod
      labels:
        app: httpd
        tier: frontend
    spec:
      containers:
        - image: httpd
          name: httpd-cont
          ports:
            - containerPort: 80
              protocol: TCP
              