apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: dev
  name: dev-resource-quota
spec:
  hard:
    pods: "2"
    requests.memory: 0.5Gi
    requests.cpu: "0.5"
    limits.memory: 1Gi
    limits.cpu: "1"