apiVersion: v1
kind: Service
metadata:
  labels:
    run: talant-ghost
  name: talant-ghost-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30081
  selector:
    run: talant-ghost
status:
  loadBalancer: {}
