apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ghost
  name: ghost
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ghost
    spec:
      containers:
      - image: ghost:alpine
        name: ghost
