apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod-nodeselector
  labels:
    app: httpd
    tier: frontend
spec:
  nodeSelector: 
    role: worker1
  containers:
    - image: httpd
      name: httpd-container