apiVersion: v1
kind: Service
metadata:
  name: httpd-deploy-service
  labels:
    app: httpd-deploy
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30087
  selector:
    app: httpd
