apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp1
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp1
        tier: frontend
    spec:
      containers:
        - image: nginx
          name: nignx-container
          ports:
            - protocol: TCP
              containerPort: 80
  selector:
    matchLabels:
      app: myapp1
      
