apiVersion: v1
kind: Pod
metadata:
  labels:
    run: polinux-stress-pod
  name: polinux-stress-pod
spec:
  containers:
  - image: polinux/stress
    name: polinux-stress-pod
    resources:
      requests:
        cpu: 0.1
        memory: "100Mi"
      limits:
        cpu: 0.4
        memory: "256Mi"
