apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: dev
  name: dev-resource-quota
spec:
  hard:
    pods: "6"
    requests.memory: 1Gi
    requests.cpu: "1"
    limits.memory: 3Gi
    limits.cpu: "2"
